# Generated by Django 6.0.4 on 2026-04-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('url_photo', models.URLField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('unlock', models.TextField()),
                ('package_cards', models.ManyToManyField(related_name='package_cards', to='cards.card')),
            ],
        ),
    ]
