# Generated by Django 6.0.4 on 2026-04-23 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_options'),
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nome')),
                ('cover_url', models.URLField(max_length=500, verbose_name='URL da capa')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(9999)], verbose_name='preço')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('unlock_requirements', models.TextField(blank=True, help_text='Texto livre: como o jogador desbloqueia ou obtém este pacote.', verbose_name='requisitos de desbloqueio')),
                ('cards', models.ManyToManyField(blank=True, related_name='packs', to='cards.card', verbose_name='cartas')),
            ],
        ),
        migrations.DeleteModel(
            name='Packs',
        ),
    ]
