# Generated by Django 6.0.4 on 2026-04-20 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('card_type', models.CharField(choices=[('normal_monster', 'Normal Monster'), ('effect_monster', 'Effect Monster'), ('fusion_monster', 'Fusion Monster'), ('ritual_monster', 'Ritual Monster'), ('spell', 'Spell'), ('trap', 'Trap')], max_length=32, verbose_name='tipo de carta')),
                ('attribute', models.CharField(blank=True, choices=[('light', 'LIGHT'), ('dark', 'DARK'), ('earth', 'EARTH'), ('water', 'WATER'), ('fire', 'FIRE'), ('wind', 'WIND'), ('divine', 'DIVINE')], max_length=16, verbose_name='atributo')),
                ('monster_type', models.CharField(blank=True, choices=[('aqua', 'Aqua'), ('beast', 'Beast'), ('beast_warrior', 'Beast-Warrior'), ('dinosaur', 'Dinosaur'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('fiend', 'Fiend'), ('fish', 'Fish'), ('insect', 'Insect'), ('machine', 'Machine'), ('plant', 'Plant'), ('psychic', 'Psychic'), ('pyro', 'Pyro'), ('reptile', 'Reptile'), ('rock', 'Rock'), ('sea_serpent', 'Sea Serpent'), ('spellcaster', 'Spellcaster'), ('thunder', 'Thunder'), ('warrior', 'Warrior'), ('winged_beast', 'Winged Beast'), ('divine_beast', 'Divine-Beast'), ('zombie', 'Zombie'), ('cyberse', 'Cyberse'), ('wyrm', 'Wyrm')], max_length=32, verbose_name='tipo de monstro')),
                ('description', models.TextField(blank=True, verbose_name='descrição / efeito')),
                ('attack', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='ATK')),
                ('defense', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='DEF')),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='nível / rank')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('super_rare', 'Super Rare'), ('ultra_rare', 'Ultra Rare'), ('secret_rare', 'Secret Rare')], default='common', max_length=32, verbose_name='raridade')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='cards/', verbose_name='imagem')),
            ],
            options={
                'verbose_name': 'carta',
                'verbose_name_plural': 'cartas',
                'ordering': ['name'],
            },
        ),
    ]
