# Generated by Django 6.0.4 on 2026-04-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
    ]
